version: "3.1"
services:
  server:
    build: .
    depends_on:
      - db
    # we didn't copy env file into the image, but inject from this field
    env_file: .env
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
  db:
    image: postgres
    restart: always
    volumes:
      - 15s-music-db:/var/lib/postgresql/data
      - ./dump-files:/dump-files
    environment:
      - POSTGRES_PASSWORD=${DatabasePW}
      - POSTGRES_DB=${DatabaseName}
    expose:
      - "5432"
    ports:
      - "${DB_EXPORINT_PORT}:5432"
volumes:
  15s-music-db:
